/* Generated by Yosys 0.18+10 (git sha1 f8419a600, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

module and2(a, b, c);
  input a;
  wire a;
  input b;
  wire b;
  output c;
  wire c;
  assign c = 4'b1000 >> { b, a };
endmodule
