/**************************************************************************************************
* Copyright (c) 1997-2022 Flexera. All Rights Reserved.
**************************************************************************************************/
/*
 *
 *	Function:	l_context array -- English context strings
 *
 *
 *	Try to make these < 15 characters long
 */
/* NOERROR */		0,
/* NOCONFFILE */	"Filename",
/* BADFILE */		"License text",
/* NOSERVER */		"Hostname",
/* MAXUSERS */		0,
/* NOFEATURE */		0,
/* NOSERVICE */		0,
/* NOSOCKET */		0,
/* BADCODE */		0,
/* NOTTHISHOST */	"Hostid",
/* LONGGONE */		"Expire date",
/* BADDATE */		"Date text",
/* BADCOMM */		"Hostname",
/* NO_SERVER_IN_FILE */	0,
/* BADHOST */		"Hostname",
/* CANTCONNECT */	"Server name",
/* CANTREAD */		"Hostname",
/* CANTWRITE */		"Hostname",
/* NOSERVSUPP */	"Server name",
/* SELECTERR */		0,
/* SERVBUSY */		0,
/* OLDVER */		"Application version > License version",
/* CHECKINBAD */	0,
/* BUSYNEWSERV */	0,
/* USERSQUEUED */	0,
/* SERVLONGGONE */	0,
/* TOOMANY */		0,
/* CANTREADKMEM */	0,
/* CANTREADVMUNIX */	0,
/* CANTFINDETHER */	0,
/* NOREADLIC */		"Hostname",
/* TOOEARLY */		"Start date",
/* NOSUCHATTR */	0,
/* BADHANDSHAKE */	0,
/* CLOCKBAD */		0,
/* FEATQUEUE */		0,
/* FEATCORRUPT */	0,
/* BADFEATPARAM */	0,
/* FEATEXCLUDE */	0,
/* FEATNOTINCLUDE */	0,
/* CANTMALLOC */	0,
/* NEVERCHECKOUT */	0,
/* BADPARAM */		0,
/* NOKEYDATA */		0,
/* BADKEYDATA */	0,
/* FUNCNOTAVAIL */	0,
/* DEMOKIT */		0,
/* NOCLOCKCHECK */	0,
/* BADPLATFORM */	0,
/* DATE_TOOBIG */	0,
/* EXPIREDKEYS */	0,
/* NOFLEXLMINIT */	0,
/* NOSERVRESP */	0,
/* CHECKOUTFILTERED */	0,
/* NOFEATSET */		0,
/* BADFEATSET */	0,
/* CANTCOMPUTEFEATSET */ 0,
/* SOCKETFAIL */ 	0,
/* SETSOCKFAIL */	0,
/* BADCHECKSUM */	0,
/* SERVBADCHECKSUM */	0,
/* SERVNOREADLIC */	"Server name",
/* NONETWORK */		0,
/* NOTLICADMIN */	0,
/* REMOVETOOSOON */	0,
/* BADVENDORDATA */	0,
/* LIBRARYMISMATCH */	0,
/* NONETOBORROW */	0,
/* NOBORROWSUPP */	0,
/* LM_NOTONSERVER */ 	"Hostid",
/* LM_BORROWLOCKED */	"locked counter != requested",
/* BAD_TZ */		0,
/* OLDVENDORDATA */	0,
/* LOCALFILTER */	0,
/* LM_ENDPATH */	0,
/* LM_VMS_SETIMR_FAILED */ 0,
/* LM_INTERNAL_ERROR */	0,
/* LM_BAD_VERSION */	"Version text",
/* LM_NOADMINAPI */	0,
/* LM_NOFILEOPS */	0,
/* LM_NODATAFILE */	0,
/* LM_NOFILEVSEND */	0,
/* LM_BADPKG */	 	"PACKAGE text",
/* LM_SERVOLDVER */	"Server name",
/* LM_USERBASED	*/ 	0,
/* LM_NOSERVCAP	*/ 	0,
/* LM_OBJECTUSED */	0,
/* LM_MAXLIMIT */	0,
/* LM_BADSYSDATE */	0,
/* LM_PLATNOTLIC */	"Platforms",
/* LM_FUTURE_FILE */ 	"License text",
/* LM_DEFAULT_SEEDS */ 	0,
/* LM_BADATTRS */   0,
/* LM_POOL */ 		0,
/* LM_LGEN_VER */     0,
/* LM_NOT_THIS_HOST */  0,
/* LM_HOSTDOWN */ 	"Hostname",
/* LM_VENDOR_DOWN */ 	"Vendor:Host",
/* LM_CANT_DECIMAL */ 	"License text",
/* LM_BADDECFILE */ 	"License text",
/* LM_REMOVE_LINGER */ 	0,
/* LM_RESVFOROTHERS */ 	0,
/* LM_BORROW_ERROR */ 	"FLEXid",
/* LM_TSOK_ERR */ 	0,
/* LM_BORROWED_TOOLONG */ "Requested hours > allowed hours",
/* LM_UNBORROWED_ALREADY */ 0,
/* LM_SERVER_MAXED_OUT */ 0,
/* LM_BORROWNOCOMP */ 0,
/* LM_BORROW_METEREMPTY */ 0,
/* LM_NOBORROW_METER */ 0,
/* LM_NODONGLE */ 0,
/* LM_NORESLINK */ 0,
/* LM_NODONGLEDRIVER */ "Dongle Type",
/* LM_FLEXLOCK2CKOUT */ 0,
/* LM_SIGN_REQ */ "Missing",
/* LM_PUBKEY_ERR */ 0,
/* LM_NOTRLSUPPORT */ 0,
/* LM_BORROW_LINGER_ERR */ 0,
/* LM_BORROW_EXPIRED */ 0,
/* LM_MUST_BE_LOCAL */ "This host is not server host",
/* LM_BORROW_DOWN */ 0,
/* LM_BORROW_DOWN */ "Hostids",
/* LM_BORROW_DELETE_ERR */ 0,
/* LM_BORROW_RETURN_EARLY_ERR */	0,
/* LM_BORROW_RETURN_SERVER_ERR */	0,
/*	LM_CANT_CHECKOUT_JUST_PACKAGE */	0,
/*	LM_COMPOSITEID_INIT_ERR */	0,
/*	LM_COMPOSITEID_ITEM_ERR */	0,
/*	LM_BORROW_MATCH_ERR */	0,
/*	LM_NULLPOINTER */	0,
/*	LM_BADHANDLE */		0,
/*	LM_EMPTYSTRING */	0,
/*	LM_BADMEMORYACCESS */	0,
/*	LM_NOTSUPPORTED */	0,
/*	LM_NULLJOBHANDLE */	0,
/*	LM_EVENTLOG_INIT_ERR */	0,
/*	LM_EVENTLOG_DISABLED */	0,
/*	LM_EVENTLOG_WRITE_ERR */	0,
/*	LM_BADINDEX */		0,
/* LM_TIMEOUT  */ 0,
/* LM_BADCOMMAND */			0,
/* LM_SOCKET_BROKEN_PIPE */ 0,
/* LM_INVALID_SIGNATURE	*/ 0,
/* LM_UNCOUNTED_NOT_SUPPORTED */ 0,
/* LM_REDUNDANT_SIGNATURES */ 0,
/* LM_BADCODE_V71_LK */ 0,
/* LM_BADCODE_V71_SIGN */ 0,
/* LM_BADCODE_V80_LK */ 0,
/* LM_BADCODE_V80_SIGN */ 0,
/* LM_BADCODE_V81_LK */ 0,
/* LM_BADCODE_V81_SIGN */ 0,
/* LM_BADCODE_V81_SIGN2 */ 0,
/* LM_BADCODE_V84_LK */ 0,
/* LM_BADCODE_V84_SIGN */ 0,
/* LM_BADCODE_V84_SIGN2 */ 0,
/* LM_LK_REQ */ 0,
/* LM_BADAUTH */ 0,
/* LM_REPAIR_NEEDED */ 0,
/* LM_TS_OPEN */ 0,
/* LM_BAD_FULFILLMENT */ 0,
/* LM_BAD_ACTREQ */ 0,
/* LM_TS_NO_FULFILL_MATCH */ 0,
/* LM_BAD_ACT_RESP */	0,
/* LM_CANTRETURN */	0,
/* LM_RETURNEXCEEDSMAX */ 0,
/* LM_NO_REPAIRS_LEFT */ 0,
/* LM_NOT_ALLOWED */ 0,
/* ENTLEXCLUDE */	0,
/* ENTLNOTINCLUDE */	0,
/* LM_ACTIVATION */ 0,
/* LM_TS_BADDATE */ 0,
/* LM_ENCRYPTION_FAILED */ 0,
/* LM_DECRYPTION_FAILED */0,
/* LM_BADCONTEXT */ 0,
/* LM_SUPERSEDE_CONFLICT */ 0,
/* LM_INVALID_SUPERSEDE_SIGN */ 0,
/* LM_SUPERSEDE_SIGN_EMPTYSTRING */ 0,
/* LM_ONE_TSOK_PLATFORM_ERR */ 0,
/* LM_ONE_TSOK_MTX_ERR */ 0, 
/* LM_ONE_TSOK_ERR */ 0,
/* LM_SSIDNULL */ 0,
/* LM_SMTXNOTREL */ 0,
/* LM_MTXNOPERM   */ 0,
/* LM_COMPOSITEID_ETHER_ERR   */ 0,
/* LM_LIC_FILE_CHAR_EXCEED  */ 0,
/* LM_TZ_INVALID_SYNTAX */ 0,
/* LM_TZ_INVALID_TZONE_SPEC */ 0,
/* LM_TZ_INVALID_TZONE_INFO   */ 0,
/* LM_TZ_UNAUTHORIZED */ 0,
/* LM_INVALID_VM_PLATFORMS */ 0,
/* LM_VM_PHYSICAL_ONLY */ 0,
/* LM_VM_VIRTUAL_ONLY */ 0,
/* LM_VM_NOT_SUPPORT */ 0,
/* LM_VM_BAD_KEY */ 0,
/* LM_MAXLIMIT_EXCEED */ 0,
/* LM_BA_API_INTERNAL_ERROR */ 0,
/* LM_BA_COMM_ERROR */ 0,
/* LM_INVALID_BA_VERSION */ 0,
/* LM_UNSUPPORTED_FEATURE_HOSTID */ 0,
/* LM_SERVERQUERY_LOAD_REQUEST_FAILED */ 0,
/* LM_SERVERQUERY_RESPONSE_FAILED */ 0,
/* LM_INVALID_IPADDRESS */ 0,
/* LM_UNRESOLVED_FEATURE */ 0,
/* LM_TS_GET_TOTAL_FEAT_COUNT_FAILED */ 0,
/* LM_TS_ACT_RECLAIM_NOT_ALLOWED */ 0,
/* LM_TS_ACT_RECLAIM_FAILED */ 0,
/* LM_TS_ACT_RECLAIM_NO_DR_FOUND */ 0,
/* LM_TS_ACT_RECLAIM_LS_TS_NOT_SUPPORTED */ 0,
/* LM_TS_SAVE_ERROR */ 0,
/* LM_MAXSERVERS*/ 0,
/* LM_LICSRVC_FAILED*/ 0,
/* LM_NO_VMATTR_PHY_SYS*/ 0,
/* LM_LIC_SVC_DISABLED */ 0,
/* LM_LIC_SVC_NOTINSTALLED */  0,
/* LM_LIC_SVC_VER_ERR */  0,
/* LM_VM_HOSTID_NOT_AVAILABLE */  0,
/* LM_COAVAIL_RECONN_NOT_ALL_CNT_AVAIL */ 0, 
/* LM_COAVAIL_FLAG_NOT_SUPPORTED */ 0, 
/* LM_COAVAIL_PACKAGE_NOT_SUPPORTED */ 0, 
/* LM_COAVAIL_UNSUPPORTED */ 0,
/* LM_ONLY_TS_ALLOWED */ 0,
/* LM_TRANSFER_TO_SELF_NOT_ALLOWED */ 0,
/* LM_HOSTID_UNSUPPORTED */ 0,
/* LM_LIC_SVC_REINSTALL_SVC */ 0, 
/* LM_LIC_SVC_NOT_AVAILABLE */ 0,
/* LM_LIC_SVC_COMMS_ERROR */ 0,
/* LM_TPM_LICSRVC_FAILED	*/ 0, 
/* LM_TPM_VERSION_UNSUPPORTED	*/ 0, 
/* LM_TPM_DISABLED				*/ 0, 
/* LM_TPM_PROPS_NOT_AVAILABLE  */ 0, 
/* LM_TPM_HOSTID_NOT_AVAILABLE   */ 0, 
/* LM_TPM_PLATFORM_UNSUPPORTED  */ 0,
/* LM_TPM_UNKNOWN_ERROR */         0,
/* LM_AMZ_INIT_ERR              */ 0,
/* LM_AMZ_NOT_EC2               */ 0, 
/* LM_3STS_ACTIVATION_NOT_ALLOWED */ 0,
/* LM_LMBORROWL_FOR_HYPHEN_FEATURE */ 0,
/* LM_VD_MAX_CLIENTS_REACHED */ "VD connections",
/* LM_CHECKOUTDATA_TOO_LONG */ "Checkout Data String is too long",
/* LM_CHECKOUTDATA_TOO_MANY */ "Checkout Data String exceeds the limit",
/* LM_VSEND_ASYNC_NOT_AVAILABLE */       "The server does not support asynchronous lc_vsend processing",
/* LM_VSEND_ASYNC_BUSY   */              "There is an asynchronous message currently either queued or executing",
/* LM_VSEND_INVALID_MESSSAGE  */         "The lc_vsend message is invalid",
/* LM_VSEND_NO_MESSSAGE  */              "There is no message response either pending or available on the server",
/* LM_INVALID_FILE_EXTN */ "Invalid license file extension",
/* LM_UNSUPPORTED_LICENSE_FILE_ENCODING */ "Unsupported license file encoding",
/* LM_INVALID_VENDOR_NAME */ "Invalid Vendor/ Daemon name in the license file",
/* LM_NO_VENDOR_IN_FILE */ "No Vendor/Daemon line in license file",
/* LM_INVALID_VENDOR_PORT */ "Vendor ports are not in range in license file",
/* LM_VENDOR_NOT_SERVED */ "Vendor name mentioned is not served by the lmgrd",
/* LM_FEATURE_INVALID_LICENSE_KEY */ "Feature Line license key is invalid",
/* LM_FEATURE_NOT_FOR_VENDOR */ "Feature line is not for the current vendor",
/* LM_FEATURE_FORMAT_INVALID */ "Feature line format is invalid",
/* LM_INVALID_KEYWORD_IN_LICENSE_FILE */ "Few keywords in the license file are invalid.",
/* LM_MAX_LICFILE_SIZE */ "The license file size has exceeded the maximum allowed limit of 1 MB for validation.",
/* LM_FILE_EXISTS */ "File names passed should be different.",
/* LM_FILE_CANNOT_OPEN */ "Unable to open the file.",
/* LM_FIELDS_RSV_FAILED */ 0,
/* LM_UNSUP_RSV_KEY */ 0,
/* LM_INVALID_LIC_COUNT */	0,
/* LM_UNCOUNTED_LIC */ 0,
/* LM_RSV_ID_NOT_EXIST */ 0,
/* LM_RSV_INVALID_DURATION */ 0,
/* LM_SUITE_RESERVED_NOT_SUPP */ 0,
/* LM_NO_SUCH_FILE */ 0,
/* LM_FILE_EMPTY */ 0,
/* LM_NO_READ_PERMISSION */ 0,
/* LM_RESERVE_LEN_EXCEED */ 0,
/* LM_MAX_RESERVE_LINES */ 0,
/* LM_MISSING_MARKERS */ 0,
/* LM_DOCKER_UNSUPPORTED_PLATFORM */ "Not running under docker platform",
/* LM_DOCKER_ID_NOT_AVAILABLE */ "Docker Container ID not available.",
/* LM_TXN_NOEXISTS */ "Transaction not found",
/* LM_TXN_ATTR_NOTSET */ "Transaction entry attribute is not set",
/* LM_LOCAL_CHECK_FAILED */ "Local checks for checkout failed",
/* LM_NOT_DUP_LOCALTEST */ 0,
/* LM_TXN_TOO_MANY_ENTRY */ "Too many entry for batch checkout",
/* LM_NO_ECOMMS_SUPP */ "Encrypted communications not enabled",
/* LM_ECOMMS_ERROR */ "Encrypted communications have failed"

