/* Generated by Yosys 0.18+10 (git sha1 daf9624a5, gcc 11.2.0 -fPIC -Os) */

module i_bufds(clk, I_N, I_P, oe, buffered_output);
  input I_N;
  input I_P;
  output buffered_output;
  input clk;
  input oe;
  (* keep = 32'h00000001 *)
  wire _00_;
  (* keep = 32'h00000001 *)
  wire _01_;
  (* keep = 32'h00000001 *)
  wire _02_;
  (* keep = 32'h00000001 *)
  wire _03_;
  (* keep = 32'h00000001 *)
  wire _04_;
  (* keep = 32'h00000001 *)
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:3" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:3" *)
  wire I_N;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:4" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:4" *)
  wire I_P;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:9" *)
  wire buf1_result;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:6" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:6" *)
  wire buffered_output;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:2" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:2" *)
  wire clk;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:10" *)
  wire [1:0] cnt;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:5" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:5" *)
  wire oe;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/i_buf_ds/i_bufds.sv:9" *)
  wire result;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/06_23_2023_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  dffre _08_ (
    .C(clk),
    .D(_06_),
    .E(oe),
    .Q(cnt[0]),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/06_23_2023_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  dffre _09_ (
    .C(clk),
    .D(_07_),
    .E(oe),
    .Q(cnt[1]),
    .R(1'h1)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'h00000002)
  ) _10_ (
    .A(cnt),
    .Y(_07_)
  );
  \$lut  #(
    .LUT(16'h7dc0),
    .WIDTH(32'h00000004)
  ) _11_ (
    .A({ buf1_result, oe, cnt }),
    .Y(result)
  );
  \$lut  #(
    .LUT(2'h1),
    .WIDTH(32'h00000001)
  ) _12_ (
    .A(cnt[0]),
    .Y(_06_)
  );
  I_BUF_DS #(
    .DELAY(1'h0),
    .SLEW_RATE("SLOW")
  ) myBuffer0 (
    .C(clk),
    .I_N(I_N),
    .I_P(I_P),
    .O(buf1_result),
    .OE(oe)
  );
  I_BUF_DS #(
    .DELAY(1'h0),
    .SLEW_RATE("SLOW")
  ) myBuffer1 (
    .C(clk),
    .I_N(1'h0),
    .I_P(result),
    .O(buffered_output),
    .OE(oe)
  );
  assign _00_ = cnt[0];
  assign _01_ = cnt[1];
  assign _02_ = cnt[0];
  assign _03_ = cnt[1];
  assign _04_ = cnt[0];
  assign _05_ = cnt[1];
endmodule
