/* Generated by Yosys 0.18+10 (git sha1 4dc4c46c3, gcc 11.2.0 -fPIC -Os) */

module adder(a, b, c);
  input a;
  input b;
  output c;
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:2" *)
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:2" *)
  wire a;
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:7" *)
  wire a_in;
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:3" *)
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:3" *)
  wire b;
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:7" *)
  wire b_in;
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:4" *)
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:4" *)
  wire c;
  (* src = "/nfs_scratch/zafar/RAPTOR_IP/Raptor_IP/Raptor_IP.srcs/sources_1/adder.sv:7" *)
  wire c_in;
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'h00000002)
  ) _0_ (
    .A({ a_in, b_in }),
    .Y(c_in)
  );
  \I_BUF(PULL_UP_DOWN="FALSE",REG_EN="FALSE")  #(
    .DELAY(1'h0),
    .PULL_UP_DOWN(7'h00),
    .REG_EN(7'h00),
    .SLEW_RATE(6'h00)
  ) a_sig (
    .I(a),
    .O(a_in)       // Input to fabric
  );
  \I_BUF(PULL_UP_DOWN="FALSE",REG_EN="FALSE")  #(
    .DELAY(1'h0),
    .PULL_UP_DOWN(7'h00),
    .REG_EN(7'h00),
    .SLEW_RATE(6'h00)
  ) b_sig (
    .I(b),
    .O(b_in)       // Input to fabric
  );
  \O_BUF(PULL_UP_DOWN="FALSE",REG_EN="FALSE")  #(
    .DELAY(1'h0),
    .PULL_UP_DOWN(7'h00),
    .REG_EN(7'h00),
    .SLEW_RATE(6'h00)
  ) c_sig (
    .I(c_in),     // Output from fabric
    .O(c)
  );
endmodule
