/* Generated by Yosys 0.18+10 (git sha1 daf9624a5, gcc 11.2.0 -fPIC -Os) */

module xor_gate(a, oe, y);
  input a;
  input oe;
  output y;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft/xor_gate.sv:2" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft/xor_gate.sv:2" *)
  wire a;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft/xor_gate.sv:3" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft/xor_gate.sv:3" *)
  wire oe;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft/xor_gate.sv:8" *)
  wire x;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft/xor_gate.sv:4" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft/xor_gate.sv:4" *)
  wire y;
  \$lut  #(
    .LUT(4'h4),
    .WIDTH(32'h00000002)
  ) _0_ (
    .A({ oe, a }),
    .Y(x)
  );
  O_BUFT #(
    .DELAY(1'h0),
    .SLEW_RATE("SLOW")
  ) myBuffer (
    .I(x),
    .O(y),
    .OE(oe)
  );
endmodule
