#!/bin/bash
# Raptor environment setup script - 64-bit Linux
# Copyright(c) 2021-2024 Rapid Silicon
# All licenses available in $RAPTOR_PATH/share/raptor/licenses
# Version 1.0

RETURN_PATH=`pwd`
SCRIPT_PATH=`dirname $BASH_SOURCE`
RAPTOR_PATH=`( cd "$SCRIPT_PATH" && pwd )`

[ -f $RAPTOR_PATH/../.raptorenv_lin64.sh ] && source $RAPTOR_PATH/../.raptorenv_lin64.sh
[ -f $RAPTOR_PATH/bin/default_lic_path ] && source $RAPTOR_PATH/bin/default_lic_path


iswsl() {
    if [[ -s /etc/wsl.conf ]] || \
       grep -qi "wsl2" /proc/version || \
       uname -r | grep -qi "wsl2" || \
       [ -n "$WSL_DISTRO_NAME" ] || \
       which powershell.exe &> /dev/null; then
        echo "WSL"
    else
        echo ""
    fi
}

# Function to detect the environment
detect_environment() {
    # Check if running inside WSL
    result=$(iswsl)
    if [ "$result" == "WSL" ]; then
    echo "WSL"
    # Check if running inside Docker
    elif [ -f "/.dockerenv" ]; then
        echo "Docker"
    # Assume native Linux
    else
        echo "Native"
    fi
}

environment=$(detect_environment)
if [ "$environment" == "Native" ]; then
        RAPTOR_EXE=raptorm.exe
else
        RAPTOR_EXE=raptor.exe
fi

$RAPTOR_PATH/bin/$RAPTOR_EXE "$@"


