/* Generated by Yosys 0.18+10 (git sha1 daf9624a5, gcc 11.2.0 -fPIC -Os) */

module and_gate(a, clk, en, y);
  input a;
  input clk;
  input en;
  output y;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:19" *)
  wire N_signal;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:20" *)
  wire P_signal;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:3" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:3" *)
  wire a;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:4" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:4" *)
  wire clk;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:5" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:5" *)
  wire en;
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:7" *)
  (* src = "/nfs_scratch/zafar/FPGA_PRIMITIVE_TEST_CASE/o_buft_ds/and_gate.sv:7" *)
  wire y;
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'h00000002)
  ) _0_ (
    .A({ P_signal, N_signal }),
    .Y(y)
  );
  O_BUFT_DS #(
    .DELAY(1'h0),
    .SLEW_RATE("SLOW")
  ) myBuffer (
    .C(clk),
    .I(a),
    .OE(en),
    .O_N(N_signal),
    .O_P(P_signal)
  );
endmodule
